osx_image: xcode8.2
language: generic
matrix:
  include:
    - os: osx
      env:
        - PLATFORM=swiftpm
    - os: linux
      sudo: required
      dist: trusty
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./ci/setup_linux.sh; fi
script:
  - . ./ci/swiftpm.sh
